# Generated by Django 3.2.16 on 2022-10-13 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectTable',
            new_name='Room',
        ),
    ]
